---
title: "Bayesian SITAR model - An introduction"
author: "Satpal Sandhu"
date: '`r format(Sys.time(), "%B %d, %Y")`'
bibliography: [Bayesian_SITAR_An_Introduction.bib, packages.bib, REFERENCES.bib]
csl: apa-7th-edition.csl
link-citations: yes
colorlinks: true
lang: en-US
zotero: true
header-includes:
   - \setlength\parindent{30pt}\setlength{\parskip}{0.0pt plus 1.0pt}
   - \pagenumbering{gobble}
   - \setlength{\headheight}{47pt}
   - \usepackage{float}
   - \floatplacement{figure}{H}
output: 
  bookdown::html_document2:
    #  base_format: rmarkdown::html_vignette
      toc: yes
      number_sections: true
      toc_depth: 2
      toc_float: false
      highlight: tango
      pandoc_args: 
      - --shift-heading-level-by=-1
      - --lua-filter=parse-html-links.lua
      # css: bsitar_style.css
      code_folding: hide
      fig_caption: yes
      keep_tex: yes
linkcolor:  blue
urlcolor: blue
citecolor: magenta
vignette: >
  %\VignetteIndexEntry{Bayesian SITAR model - An introduction}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
params:
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
linestretch: 1.5
mainfont: "Times New Roman"
monofont: "Monaco"
fontsize: 12pt
geometry:
- top=2cm
- left=2.5cm
- right=2.5cm
- bottom=3.5cm
papersize: a4
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
 # eval = if (isTRUE(exists("params"))) params$EVAL else FALSE,
  dev = "jpeg",
  dpi = 100,
  fig.asp = 0.8,
  fig.width = 5,
  out.width = "60%",
  fig.align = "center"
)
```

```{=tex}
\newpage
\pagenumbering{arabic}
```
```{css, echo=FALSE}
p {
	text-indent: 0em;
}

p + p {
	text-indent: 2em;
}
```

\newpage

## Introduction

Human physical growth is not a smooth progression through time, but is inherently dynamic in nature. Growth proceeds in a series of spurts which reflect an increase in the growth velocity [@RN5278; @RN6913; @RN7906]. The adolescent growth spurt (also known as the pubertal growth spurt) is experienced by all individuals and is the most readily recognized aspect of adolescence. A clear knowledge of the growth dynamics during adolescence is essential when planning treatment to correct skeletal discrepancies such as scoliosis in which the spine has a sideways curve [@RN2761; @RN7982]. Similarly, the timing of the peak growth velocity spurt is an important factor to be considered when initiating growth modification procedures to correct skeletal malocclusion characterized by discrepancies in the jaw size [@RN7058; @RN6934; @RN7058a]

As the notion of change is central in studying growth, a correct view of the growth dynamics and the relationship between different growth phases can only be obtained from longitudinal growth data [@RN6071; @RN5278a]. Analysis of longitudinal growth data using an appropriate statistical method allows description of growth trajectories (distance and derivatives) and estimation of the timing and intensity of the adolescent growth spurt. Unlike in early years when linear growth curve model (GCMs) based on conventional polynomials were extensively used for studying human growth [@RN6217], the nonlinear nonlinear mixed effect are now gaining popularity in modelling longitudinal skeletal growth data such as height [@RN6217; @RN6071a].

## SITAR growth curve model - an overview

The super imposition by translation and rotation (SITAR) model [@Cole2010] is a shape-invariant nonlinear mixed effect growth curve model that fits a population average (i.e., mean average) curve to the data and aligns each individual's growth trajectory to the population average curve by a set of three random effects [@Cole2010; @cole2018]: the size relative to the mean growth curve (vertical shift), the timing of the adolescent growth spurt relative to the mean age at peak growth velocity (horizontal shift), and the intensity of the growth velocity, i.e., the relative rate at which individuals grow during the adolescent growth spurt in comparison to the mean growth intensity (horizontal stretch). The concept of shape invariant model (SIM) was first described by [@Lindstrom1995] and later used by [@Beath2007] [@Beath2007] for modelling infant growth data (birth to 2 years). The current version of the SITAR model that we describe below is developed by [@Cole2010].

The SITAR is particularly useful in modelling human physical growth during adolescence. Recent studies have used SITAR for analyzing height and weight data [@nembidzaneUsingSITARMethod2020; @mansukoskiLifeCourseAssociations2019; @coleFiftyYearsChild2018; @riddellClassifyingGestationalWeight2017; @riddell2017]and also to study jaw growth during adolescence [@Sandhu2020]. All these previous studies estimated SITAR model within the frequentist framework as implemented in the R package, the *sitar* package [@R-sitar].

Consider a dataset comprised of $j$ individuals $(j = 1, . . ,j)$ where individual $j$ provides $n_j$ measurements ($i = 1, . . , n_j$) of height ($y_{ij}$) recorded at age, $x_{ij}$.

```{=tex}
\begin{equation}
y_{ij}=\alpha_{0\ }+\alpha_{j\ }+\sum_{r=1}^{p-1}{\beta_r\mathbf{Spl}\left(\frac{x_{ij}-\bar{x_{ij}}-\left(\zeta_0+\zeta_j\right)}{e^{-\ \left(\left.\ \gamma_0+\ \gamma_j\right)\right.}}\right)}+e_{ij}
(\#eq:1)
\end{equation}
```
Where **Spl(.)** is the natural cubic spline function that generates the spline design matrix and $\beta_1,.,\beta_{p-1}$ are spline regression coefficient for the mean curve with $\alpha_0$, $\zeta_0$, $\gamma_0$ as the population average size, timing, and intensity parameters. By default, the predictor, age ($x_{ij}$) is mean centered by subtracting the mean age ($\bar{x}$) from it where $\bar{x} = \frac{1}{n} \sum_{i=1}^{n}x_{i.}$. The individual-specific random effects for size $(\alpha_j)$, timing $(\zeta_j)$ and intensity $(\gamma_j)$ describe how an individual's growth trajectory differs from the mean growth curve. The residuals $e_{ij}$ are also assumed to be normally distributed with zero mean and residual variance parameter $\sigma^2$ and are independent from the random effects. The random effects are assumed to be multivariate normally distributed with zero means and variance-covariance matrix $\Omega_2$. The $\Omega_2$ is unstructured (i.e., distinct variances and covariances between random effects) as follows:

```{=tex}
\begin{equation}
\begin{matrix}&\\&\\\left(\begin{matrix}\begin{matrix}\alpha_j\\\zeta_j\\\gamma_j\\\end{matrix}\\\end{matrix}\right)&\sim M V N\left(\left(\begin{matrix}\begin{matrix}0\\0\\0\\\end{matrix}\\\end{matrix}\right),\left(\begin{matrix}\sigma_{\alpha_j}^2&\rho_{\alpha_j\zeta_j}&\rho_{\alpha_j\gamma_j}\\\rho_{\zeta_j\alpha_j}&\sigma_{\zeta_j}^2&\rho_{\zeta_j\gamma_j}\\\rho_{\gamma_j\alpha_j}&\rho_{\gamma_j\zeta_j}&\sigma_{\gamma_j}^2\\\end{matrix}\right)\right)\mathrm{,\ for\ individual\ j\ =\ 1,} \ldots\mathrm{,J} \\\end{matrix}
(\#eq:2)
\end{equation}
```
<br/>

## Model estimation - frequentist vs. Bayesian

There are two competing philosophies of model estimation [@bland1998; @Schoot2014]: the Bayesian (based on Bayes' theorem) and the frequentist (e.g., maximum likelihood estimation) approaches. While the frequentist approach was predominant in the earlier years, the advent of powerful computers has given a new impetus to the Bayesian analysis [@bland1998; @Schoot2014; @hamra2013]. As a result, Bayesian statistical methods are becoming ever more popular in applied and fundamental research. The key difference between Bayesian statistical inference and frequentest statistical methods concerns the nature of the unknown parameters. In the frequentist framework, a parameter of interest is assumed to be unknown, but fixed. That is, it is assumed that in the population there is only one true population parameter, for example, one true mean or one true regression coefficient. In the Bayesian view of subjective probability, all unknown parameters are treated as uncertain and therefore should be described by a probability distribution [@Schoot2014]. A particular attractive feature of Bayesian modelling is its ability to handle otherwise complex model specifications such as hierarchical model (i.e,., multilevel/mixed-effects models) that involve nested data structures (e.g., repeated height measurements in individuals) [@hamra2013].

There are three essential components underlying Bayesian statistics ([@bayes1763lii; @stigler1986laplace]): the *prior distribution,* the *likelihood function,* and the *posterior distribution*. The *prior distribution* refers to all knowledge available *before* seeing the data whereas the *likelihood function* expresses the information in the data given the parameters defined in the model. The third component (i.e., *posterior distribution*) is based on combining the first two components via Bayes' theorem and the results are summarized by the so-called *posterior inference*. The *posterior distribution*, therefore, reflects one's updated knowledge, balancing prior knowledge with observed data.

The task of combining these components together can yield a complex model in which the exact distribution of one or more variables is unknown and estimators that rely on assumptions of normality may perform poorly. This limitation is often mitigated by estimating the Bayesian models using Markov Chain Monte Carlo (MCMC). Unlike deterministic maximum-likelihood algorithms, MCMC is a stochastic procedure that repeatedly generates random samples that characterize the distribution of parameters of interest [@hamra2013]. The popular software platform for Bayesian estimation is the BUGS family including BUGS [@10.2307/2348941] WinBUGS [@lunn2000], OpenBUGS [@spiegelhalter2007openbugs], JAGS [@Plummer2003JAGSAP]. More recently, the software Stan has been developed to achieve higher computational and algorithmic efficiency by using the No-U-Turn Sampler (NUTS), which is an adaptive variant of Hamiltonian Monte Carlo (HMC) [@Hoffman2011; @neal2011; @gelman2015].

## Bayesian SITAR model

<!-- https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed/blob/master/14.Rmd -->

<!-- ### Conventional multilevel growth model. -->

Bayesian statistical methods are becoming ever more popular in applied and fundamental research [@Schoot2014]. Here we provide the Bayesian specification of the SITAR model described above. To get a better understanding of the data generative mechanism and for the ease of showing prior specification for each individual parameter, we re express the above model \@ref(eq:1) as as follows:

<!-- color{#A65141} -->

```{=tex}
\begin{equation}
\begin{aligned}
\text{y}_{ij} & \sim \operatorname{Normal}(\mu_{ij}, \sigma) \\
\\
\mu_{ij} & = \alpha_0+ \alpha_j+\sum_{r=1}^{p-1}{\beta_r\mathbf{Spl}\left(\frac{x_{ij}-\bar{x_{ij}}-\left(\zeta_0+\zeta_j\right)}{e^{-\ \left(\left.\ \gamma_0+\gamma_j\right)\right.}}\right)} \\
\sigma & = \sigma_\epsilon \\
\\
\begin{bmatrix} \alpha_{j} \\ \zeta_{j} \\ \gamma_{j} \end{bmatrix} & \sim {\operatorname{MVNormal}\begin{pmatrix} \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix},\ \mathbf S \mathbf R \mathbf S \end{pmatrix}} \\
\\
\mathbf S & = \begin{bmatrix} \sigma_{\alpha_j} & 0 & 0 \\ 0 &\sigma_{\zeta_j} & 0 \\ 0 &  0 & \sigma_{\gamma_j} \end{bmatrix} \\
\\
\mathbf R & = \begin{bmatrix} 1  & \rho_{\alpha_j\zeta_j} & \rho_{\alpha_j\gamma_j} \\\rho_{\zeta_j\alpha_j} & 1 & \rho_{\zeta_j\gamma_j} \\\rho_{\gamma_j\alpha_j} & \rho_{\gamma_j\zeta_j} & 1 \end{bmatrix} \\
\\
\alpha_0   & \sim \operatorname{Normal}(y_{mean},\  {y_{sd}}) \\
\zeta_0   & \sim \operatorname{Normal}(0, 2) \\
\gamma_1   & \sim \operatorname{Normal}(0, 1) \\
\beta_1 \text{,..,} \beta_r & \sim \operatorname{Normal}(0, \ \mathbf {X_{scaled}}) \\
\sigma_\epsilon & \sim \operatorname{Normal}(0, y_{sd}) \\
\mathbf R & \sim \operatorname{LKJ}(1),
\end{aligned}
(\#eq:4)
\end{equation}
```
The first formula (line) in the above equation is the probability of the outcome (likelihood) which states that the outcome is distributed with mean *mu* (see second line) and standard deviation, *sigma*. The *mu* is the function of growth curve parameters as described model \@ref(eq:1).

We follow the recomendation made in the popular packages [rstanrm](https://cran.r-project.org/web/packages/rstanarm/vignettes/priors.html) and [brms](https://rdrr.io/cran/brms/man/set_prior.html) for prior specification. Technically, the prior used in *rstanrm* and *brms* packages are data-dependent and, hence *weakly informative*. This is because the the scaling is based on the scales of the predictors and the outcome. However, the amount of information used is weak and mainly takes into account the order of magnitude of the variables. An important feature of such priors is that defaults priors are reasonable for many models fit using the *rstanrm* and *brms*.

#### References
