---
title: "Fitting Bayesian SITAR model - Univariate"
author: "Satpal Sandhu"
date: '`r format(Sys.time(), "%B %d, %Y")`'
bibliography: [bsitar_univariate.bib, packages.bib]
csl: apa-6th-edition.csl
link-citations: yes
colorlinks: true
lang: en-US
zotero: true
header-includes:
   - \setlength\parindent{30pt}\setlength{\parskip}{0.0pt plus 1.0pt}
   - \pagenumbering{gobble}
   - \setlength{\headheight}{47pt}
output: 
  bookdown::html_document2:
    #  base_format: rmarkdown::html_vignette
      toc: yes
      number_sections: true
      toc_depth: 2
      toc_float: false
      highlight: tango
      pandoc_args: 
      - --shift-heading-level-by=-1
      - --lua-filter=parse-html-links.lua
      css: bsitar_style.css
linkcolor:  blue
urlcolor: blue
citecolor: magenta
vignette: >
  %\VignetteIndexEntry{Fitting Bayesian SITAR model - Univariate}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
params:
  
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
linestretch: 1.5
mainfont: "Times New Roman"
monofont: "Monaco"
fontsize: 12pt
geometry:
- top=2cm
- left=2.5cm
- right=2.5cm
- bottom=3.5cm
papersize: a4
editor_options: 
  markdown: 
    wrap: 72
---

```{r, SETTINGS-knitr, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE,
  eval = if (isTRUE(exists("params"))) params$EVAL else FALSE,
  dev = "jpeg",
  dpi = 100,
  fig.asp = 0.8,
  fig.width = 5,
  out.width = "60%",
  fig.align = "center"
)
```

```{=tex}
\newpage
\pagenumbering{arabic}
```
## Introduction

This vignette provides an introduction on how to fit non-linear multilevel models with **brms** [@R-brms]. Non-linear models are incredibly flexible and powerful, but require much more care with respect to model specification and priors than typical generalized linear models. Ignoring group-level effects for the moment, the predictor term $\eta_n$ of a generalized linear model for observation $n$ can be written as follows:

ittststsstststs itttttt

## SITAR growth curve model

The SITAR is a shape-invariant nonlinear mixed effect growth curve model that has been specifically developed to model the biology of growth (such as increase in height and weight gain during adolescence). Bayesian statistical methods are becoming ever more popular in applied and fundamental research. The key difference between Bayesian statistical inference and frequentist (e.g., maximum likelihood estimation) statistical methods concerns the nature of the unknown parameters. In the frequentist framework, a parameter of interest is assumed to be unknown, but fixed. That is, it is assumed that in the population there is only one true population parameter, for example, one true mean or one true regression coefficient. In the Bayesian view of subjective probability, all unknown parameters are treated as uncertain and therefore should be described by a probability distribution [@Schoot2014].

## Data

models the biology of growth. To illustrate this we use the berkeley dataset to explore the growth of height in girls during puberty. If necessary, first install the sitar library.

## A Simple Non-Linear Model

We begin with a simple example using simulated data [@R-sitar]. hhh [Introduction] nnnn \@ref(Introduction) bbb [@Beath2007]

### nnn

#### References
